name : Primer pipeline

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-lastest

    steps:
      - name: Revisión repositorio
        run: echo esta ejecutando el entorno

      - name: analisis repositorio
        run: se esta analizando el repositorio

ls -la
